# marihydro\crates\mh_geo\Cargo.toml

[package]
name = "mh_geo"
version = "0.1.0"
edition = "2021"

[dependencies]
mh_foundation = { path = "../mh_foundation" }
rstar = "0.12"
serde = { version = "1.0", features = ["derive"] }